apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: project-minimal-cluster
  namespace: backend
spec:
  teamId: "project"
  volume:
    size: 1Gi
    storageClass: do-block-storage
  numberOfInstances: 1
  users:
    username:  # database owner
    - superuser
    - createdb
    username_user: []  # role for application foo
  databases:
    projectdb: username  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "13"
